import type { Metadata } from "next";
import { Montserrat, Encode_Sans_Condensed } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/toaster";

const fontSans = Montserrat({ subsets: ["latin"], variable: "--font-sans" });
const fontMono = Encode_Sans_Condensed({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          fontMono.variable,
          fontSans.className,
          "flex h-screen w-screen flex-col overflow-hidden bg-secondary p-2 sm:flex-row",
        )}
      >
        <Layout>{children}</Layout>
        <Toaster />
      </body>
    </html>
  );
}
